name: pipeline_TDW-02

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Jest
        run: npm install jest

      - name: Run tests
        run: npm test

  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Nuxt.js
        run: npm install nuxt

      - name: Build project
        run: npm run build

  format-code:
    name: Format Code
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Prettier
        run: npm install prettier

      - name: Run Prettier
        run: npx prettier --write .
