name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lista de Ficheiros
        run: ls -la
        working-directory: ${{ github.workspace }}

  setup:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Setup node env 
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 'lts/*'
          check-latest: true
        working-directory: ${{ github.workspace }}

      - name: node_modules 
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        working-directory: ${{ github.workspace }}

  install:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Dependencias
        run: npm install --prefer-offline --no-audit
        working-directory: ${{ github.workspace }}

  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Testes
        run: npm test
        working-directory: ${{ github.workspace }}

  format:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Prettier
        run: npm run prettier
        working-directory: ${{ github.workspace }}

  build:
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Build da App
        run: npm run build
        working-directory: ${{ github.workspace }}
